language: node_js
node_js:
    - 'stable'
cache:
    directories:
        - node_modules
install:
    - npm install -g codecov
    - yarn
before_script:
	- "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
script:
    - yarn build
    - fossa init
    - fossa analyze
    - yarn test && codecov
after_success:
    - fossa test
